name: stormtr
description: Track your personal storms.

dependencies:
  flutter:
    sdk: flutter
  provider: ^2.0.1+1
  cupertino_icons: ^0.1.2
  side_header_list_view: ^0.0.3
  sqflite: ^1.1.5
  path_provider: ^0.4.0
  charts_flutter: ^0.4.0
  flare_flutter: ^1.5.1
  shared_preferences: ^0.5.2+1
  animator: ^0.1.1
  

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: any

flutter_icons:
  android: true 
  image_path: "assets/icons/appIcon.png"
  ios: true
  # image_path_android: "assets/icons/appIcon.png"
  # image_path_ios: "assets/icons/appIcon.png"
  # adaptive_icon_background: "#FFFAFAFA"
  # adaptive_icon_foreground: "assets/icons/appIcon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/icons/appIcon.png
    - assets/animations/
    - assets/graphics/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: QuarmicSans
      fonts:
        - asset: assets/fonts/QuarmicSans.ttf
